# project.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deepmost"
version = "0.5.0"
authors = [
    {name = "DeepMost Innovations", email = "support@deepmostai.com"},
]
description = "Sales conversion prediction and prospecting using reinforcement learning and AI agents."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
keywords = ["sales", "prospecting", "conversion", "prediction", "reinforcement-learning", "ai", "machine-learning", "llm", "nlp", "gguf", "agents"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "torch>=2.0.0",
    "transformers>=4.40.0",
    "stable-baselines3>=2.0.0",
    "gymnasium>=0.28.0",
    "numpy>=2.0.0",
    "requests>=2.28.0",
    "tqdm>=4.60.0",
    "huggingface_hub>=0.20.0",
    "llama-cpp-python>=0.3.9",
    "openai>=1.0.0"
]

[project.optional-dependencies]
# GPU support with llama-cpp-python compiled for CUDA/Metal
gpu = [
    "llama-cpp-python[server]>=0.3.9",
]
# Prospecting feature dependencies
prospecting = [
    "smolagents[toolkit]>=1.19.0",
      "accelerate>=1.8.1"
]
# Development dependencies including all features
dev = [
    "deepmost[gpu,prospecting]", 
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "isort>=5.10.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]

[project.urls]
"Homepage" = "https://github.com/DeepMostInnovations/deepmost"
"Bug Reports" = "https://github.com/DeepMostInnovations/deepmost/issues"
"Source" = "https://github.com/DeepMostInnovations/deepmost"
"Documentation" = "https://deepmost.readthedocs.io/"
"Model Repository" = "https://huggingface.co/DeepMostInnovations"

[tool.setuptools.packages.find]
where = ["."]
include = ["deepmost*"]
exclude = ["tests*", "*.tests", "*.tests.*", "tests.*"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.md", "*.rst"]